spring:
    jpa:
        show-sql: true
    h2.console:
        enabled: true
        path: /h2-console
    datasource:
        url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=120'
        driverClassName: org.h2.Driver
        username: 'sa'
        password: ''
    flyway:
        baseline-on-migrate: true
        enabled: true
logging:
    level:
        org.springframework.transaction: TRACE
        org.springframework.data.r2dbc: DEBUG
        org.flywaydb.core: debug
        root: info